version: "3.8"

services:

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mongo
    environment:
      - PORT=8080

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo-data: